### PR TITLE
Moved entity type alter logic to RecurlyEntityTypeInfo service.

### PR DESCRIPTION
**Pull request by markdorison**
- Created entity_type service.
- Moved hook_entity_type_alter() logic to RecurlyEntityTypeInfo.

https://www.drupal.org/node/2660072

cc/ @AlannaBurke @CHROMATIC-LLC/recurly

### CODE REVIEW

**Comment by adamzimmermann** [comment]
:+1: looks good.

What does the service give us over a traditional class and what is the theory behind that best practice? i.e. what made you decide this should be a service?

**Comment by mmatsoo** [comment]
The code looks good to me, but I'm wondering about hooks being moved into services. Is this best practice that we're following, or do we have service fever?

**Comment by markdorison** [comment]
@adamzimmermann @mmatsoo There are really two things going on here:
1. Moving the logic out of procedural code and into a class.
2. Exposing that class through Symfony's service architecture.

Technically we could have done 1 without 2 but based on what I have seen elsewhere that is not best practice. Making it a service just allows us to tap into Symfony's benefits such as lazy loading and easy dependency injection. If you haven't looked at these before:
- [Services and dependency injection in Drupal 8](https://www.drupal.org/node/2133171)
- https://twitter.com/juampynr/status/692808112605036544
- [D8 workbench_moderation.module example](http://cgit.drupalcode.org/workbench_moderation/tree/workbench_moderation.module?h=8.x-1.x#n116)

**Comment by markdorison** [comment]
@adamzimmermann @mmatsoo Utilizing the service architecture instead of instantiating the class directly has benefits like: 
- Lazy loading. Is this class already instantiated? Can that instance be reused? Symfony handles that.
- Altering services. If you instantiate the class directly, other code can not modify what service is being used with a sub-class or similar.

https://www.drupal.org/node/2133171

**Comment by adamzimmermann** [comment]
@markdorison the twitter link is broken, but the other ones helped a lot. Thanks!

**Comment by markdorison** [comment]
@adamzimmermann Fixed the link.

**Pull request closed without merging**
