### PR TITLE
Fixed translate placeholder by using an alpha character instead of !.

### PR DESCRIPTION
**Pull request by tomflanagan**
Drupal.org issue: https://www.drupal.org/node/2641566
I think all that is need here is use an alpha for your placeholder

### CODE REVIEW

**Comment by markdorison** [comment]
@tomflanagan Can you provide some documentation on this? I haven't seen it before.

**Comment by tomflanagan** [comment]
@markdorison If you look at the placeholderFormat($string, array $args) function, The comments talk about it in the default of the switch. See Drupal\Component\Render\FormattableMarkup. This is the same thing D7 used to do with !, just let it pass through.

**Comment by adamzimmermann** [comment]
I am highly intrigued by this PR.

**Comment by adamzimmermann** [comment]
The docs don't say anything about `%`, `:`, or `@` being required.

> The value replaces the placeholder in $string. Sanitization and formatting will be done before replacement. 

So I guess you can use anything as a replacement placeholder, as long as it matches a key in the replacements array?

**Comment by tomflanagan** [comment]
`````` default:
          // We do not trigger an error for placeholder that start with an
          // alphabetic character.
          if (!ctype_alpha($key[0])) {
            // We trigger an error as we may want to introduce new placeholders
            // in the future without breaking backward compatibility.
            trigger_error('Invalid placeholder (' . $key . ') in string: ' . $string, E_USER_ERROR);
          }
          break;```

So that's the default in the switch statement if it isn't `%`, `:` or `@`. It just has to be an  alphabetic character to do what `!` used to.
``````

**Comment by mmatsoo** [comment]
I'm with Adam on this one: intriguing and it kind of blows my mind. A clear sentence or two of correctly placed documentation and this never would have been its own issue?

**Comment by markdorison** [comment]
@tomflanagan So you just picked the 'T' character arbitrarily or is the some kind of best practice?

**Comment by chrisfree** [comment]
What error are we talking about here?

**Comment by markdorison** [comment]
https://www.drupal.org/node/2641566

**Comment by chrisfree** [comment]
10-4. As you were.

**Comment by tomflanagan** [comment]
@markdorison Changed to `TT` per our discussion.

**Comment by adamzimmermann** [comment]
Curious as to how we decided on `TT`. Works for me, just wondered what the thinking was.

**Comment by markdorison** [comment]
@adamzimmermann My first reaction was T was too common of a character at the beginning of words. In practice this might never have actually caused a problem but could cause some confusion but I was waffling. Through talking it out with @tomflanagan it occurred to me that having two characters as the prefix might make it more clear that this was a prefix.

**Comment by ctorgalson** [comment]
The doubled-character approach seems sensible to me. This should be reasonably comprehensible (at least for English where words seldom or never start with a double-consonant, and never, except in the case of initials or acronyms begin with a doubled capital letter).

Conceivably, there are some far out edge cases where it could become unclear to _read_, but I can't really think of a way for it to go wrong in code.

**Comment by markdorison** [comment]
I think this is ready for D.O. :ok_hand:

**Comment by markdorison** [comment]
[Patch posted](https://www.drupal.org/node/2641566#comment-10792338).

**Comment by markdorison** [comment]
Committed.

**Pull request closed without merging**
