### PR TITLE
Issue #2670476: Made refund amount radios required.

### PR DESCRIPTION
**Pull request by markdorison**
https://www.drupal.org/node/2670476

### CODE REVIEW

**Comment by markdorison** [comment]
Patch posted to D.O. > https://www.drupal.org/node/2670476#comment-10874578

**Comment by mmatsoo** [comment]
@markdorison In review, the patch applied just fine and dandy and the single line `'#required' => TRUE,` looks fine, but (and this is happening all the time, I find) when I start to navigate in the admin to test the functionality, I get `Fatal error: Class 'Recurly_SubscriptionList' not found`

In `recurly.module` and `recurly.pages.inc`, in several places one can find
`$subscription_list = Recurly_SubscriptionList::getForAccount($account_code, array('per_page' => 200));`

When I grep `Recurly_SubscriptionList`, the class itself is nowhere to be found. Has this snuck in from our D8 work, or do you know if I'm missing something elementary?

**Comment by mmatsoo** [comment]
@markdorison FWIW - the exact same error occurs for me in D8 too when I tried to check the D8 version of your patch.

**Comment by markdorison** [comment]
@mmatsoo That sounds unrelated to this change, no? Can you reproduce that error without this patch? What pages do you see it on? In the subscription tab/sub-tabs or in the admin configuration area?

**Comment by mmatsoo** [comment]
@markdorison Sorry, I didn't mean to imply it had anything to do with your patch. I just wanted to bring up the issue that there seems to be some buggy code floating around. I get it, for instance, at `user/{uid}/subscription` ex. `user/2/subscription`.

I looked into it a bit more and found that `$subscription_list = Recurly_SubscriptionList::getForAccount($account_code, array('per_page' => 200));` has been around since a [commit in 2012](https://github.com/ChromaticHQ/recurly/commit/3f16ef07e1d4ad687c218c932f48464063dd0f29).

Anyway, maybe it's something particular to me. I'll keep investigating.

**Comment by markdorison** [comment]
@mmatsoo OK. Feel free to create an issue on D.O. for this.

**Comment by mmatsoo** [comment]
@markdorison Good news. I stepped away for a bit and then when I looked at it again, I realised this class is part of the recurly library, which in my carelessness I hadn't downloaded!

**Comment by ctorgalson** [comment]
Ha! Now that you mention it, I did that at least once too!

**Pull request closed without merging**
