### PR TITLE
Moved entity hooks to new RecurlyEntityOperations service.

### PR DESCRIPTION
**Pull request by markdorison**
- Created RecurlyEntityOperations service.
- Moved recurly_entity_update & recurly_entity_delete logic to
- RecurlyEntityOperations.

https://www.drupal.org/node/2660066

Used [Workbench Moderation's implementation](http://cgit.drupalcode.org/workbench_moderation/tree/workbench_moderation.module?h=8.x-1.x) as a guide. No functional changes.

cc/ @AlannaBurke @ctorgalson

### CODE REVIEW

**Comment by adamzimmermann** [comment]
I didn't review all the details, but I love to see logic being moved out of hooks!

:beers: here is to a hookless future!

**Comment by markdorison** [comment]
Thanks @adamzimmermann. More to come; I've created follow up tickets for this on D.O. to get more logic out of recurly.module.

**Comment by mmatsoo** [comment]
Looks good to me. :+1:

**Comment by markdorison** [comment]
Patch [posted to D.O.](https://www.drupal.org/node/2660066#comment-10810030)

**Pull request closed without merging**
