### PR TITLE
Change "state" strings to constants

### PR DESCRIPTION
**Pull request by mmatsoo**
Creating a patch from this should close [D.O. issue 2641570](https://www.drupal.org/node/2641570)

### CODE REVIEW

**Comment by markdorison** [comment]
This might be the right opportunity to move this code out of recurly.module and into a service like `RecurlyUrlManager` or `RecurlyTokenManager`. I have hesitated to this point only because I haven't been able to decide whether it should be `RecurlyStateManager` and contain only the constants and a `formatState()` method, or instead a more encompassing `RecurlyFormatManager` that includes all of the formatting logic:

screen shot 2016-01-14 at 12 25 43

I think I am leaning towards a `RecurlyStateManager`. Thoughts?

**Comment by mmatsoo** [comment]
@markdorison I went with a full-on refactor and created `RecurlyFormatManager`, and moved all the formatting functions there. (and updated places in the code that call those functions)

**Comment by markdorison** [comment]
@mmatsoo Why do you like this approach as opposed to discrete services broken up like a `RecurlyTokenManager`?

**Comment by mmatsoo** [comment]
As per stand-up, I'll explore breaking the bits that make sense into their own classes. So for instance, we'd have a `Coupon` class and a `Currency` class, each with its own formatting method. (ex. `Coupon->format()`)

**Pull request closed without merging**
